"""Временный Netscape cookiefile из строки Cookie для yt-dlp."""

from __future__ import annotations

import os
import tempfile
import threading

_lock = threading.Lock()
_cache: dict[str, str] = {}


def cookie_header_to_tempfile(header: str, *, domain: str = ".yandex.ru") -> str:
    header = header.strip()
    if not header:
        return ""
    with _lock:
        cached = _cache.get(header)
        if cached and os.path.isfile(cached):
            return cached
        lines = [
            "# Netscape HTTP Cookie File",
            "# generated by tg-media-bot",
            "",
        ]
        for part in header.split(";"):
            part = part.strip()
            if not part or "=" not in part:
                continue
            name, value = part.split("=", 1)
            name, value = name.strip(), value.strip()
            if not name:
                continue
            lines.append(f"{domain}\tTRUE\t/\tFALSE\t0\t{name}\t{value}")
        fd, path = tempfile.mkstemp(prefix="yandex_cookies_", suffix=".txt")
        os.close(fd)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines) + "\n")
        _cache[header] = path
        return path


def netscape_file_to_header(path: str) -> str:
    """Собрать Cookie header из Netscape-файла."""
    parts: list[str] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            cols = line.split("\t")
            if len(cols) >= 7:
                parts.append(f"{cols[5]}={cols[6]}")
    return "; ".join(parts)


def resolve_cookie_header(header: str | None, cookiefile: str | None) -> str:
    if header:
        return header.strip()
    if cookiefile and os.path.isfile(cookiefile):
        return netscape_file_to_header(cookiefile)
    return ""
